version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: my_neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
    command: neo4j-admin database import full --overwrite-destination=true --multiline-fields=true --skip-duplicate-nodes=true --nodes=Papers=/import/papers_header.csv,/import/papers.csv,/import/papers1.csv --nodes=Authors=/import/authors_header.csv,/import/authors.csv,/import/authors1.csv --relationships=WROTE=/import/relations_header.csv,/import/relations.csv,/import/relations1.csv